
install: install-dependencies run-script
	@echo "Installation and execution complete."


install-dependencies:
	@echo "Installing dependencies..."
	sudo apt-get update
    sudo apt-get install -y dialog

run-script:
	@echo "Running script..."
	./install.sh
